name: Run gradlew docker # TODO: Build Docker images for the specified target ref, optionally finding the latest release
description:

inputs:
  target-ref:
    description: 'Target ref (branch, tag, release) to scan'
    required: true
    type: string
    default: 'main'
  find-latest-release:
    description: 'Flag to find the latest version for specified `target-ref`'
    required: false
    type: boolean
    default: false

outputs:
  docker-images:
    description: A comma-separated list of Docker images built with gradlew build
    value: ${{ steps.docker-images.outputs.docker-images }}

runs:
  using: "composite"
  steps:
    - name: Checkout vuln-check scripts
      uses: actions/checkout@v4
      with:
        repository: scalar-labs/actions
        sparse-checkout: vuln-check-script
        ref: main
        path: vuln-check

    - id: prepare-target-ref
      name: Prepare target-ref
      env:
        # TODO: Script files can be moved to this action's direcoty?
        SCRIPT_PATH: ./vuln-check/vuln-check-script
      shell: bash
      run: |
        # Find the latest release name if `find-latest-release` is set to true. Use the value of `target-ref` as is otherwise.
        if [[ ${{ inputs.find-latest-release }} = 'true' ]]; then
          releases=$($SCRIPT_PATH/fetch_gh_releases "${{ github.event.repository.owner.login }}" "${{ github.event.repository.name }}")
          echo -------------
          echo "releases: $releases"
          echo -------------
          target_release=''
          if [[ -n $releases ]]; then
            target_release=$($SCRIPT_PATH/find_latest_release "${{ inputs.target-ref }}" $releases)
          fi
          if [[ -z $target_release ]]; then
            echo "Can't find a target release"
            exit 1
          fi
          echo $target_release
          echo "target-ref=$target_release" >> $GITHUB_OUTPUT
        else
          echo "target-ref=${{ inputs.target-ref }}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout the target repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.prepare-target-ref.outputs.target-ref }}

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Docker build
      shell: bash
      run: ./gradlew docker

    - name: List Docker images
      id: docker-images
      shell: bash
      run: |
        docker image ls --format '{{.Repository}}:{{.Tag}}' | tr '\n' ',' | sed 's/,$//'
        echo "docker-images=$(docker image ls --format '{{.Repository}}:{{.Tag}}' | tr '\n' ',' | sed 's/,$//')" >> $GITHUB_OUTPUT
